/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { createProductLink } from "../funcs/createProductLink.js";
import { query } from "../funcs/query.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Ionic extends ClientSDK {
    /**
     * Ionic Commerce | Create Product Link
     *
     * @remarks
     * Creates and returns a tagged affiliate link
     */
    async createProductLink(
        request: components.ProductLinkRequest,
        security: operations.CreateProductLinkSecurity,
        options?: RequestOptions
    ): Promise<operations.CreateProductLinkResponse> {
        return unwrapAsync(createProductLink(this, request, security, options));
    }

    /**
     * Product Search
     *
     * @remarks
     * API for searching for products & recommendations.
     */
    async query(
        request: components.QueryAPIRequest,
        security: operations.QuerySecurity,
        options?: RequestOptions
    ): Promise<operations.QueryResponse> {
        return unwrapAsync(query(this, request, security, options));
    }
}
