/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type CreateProductLinkSecurity = {
    apiKeyHeader?: string | undefined;
    apiKeyQuery?: string | undefined;
};

export type CreateProductLinkResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Successful Response
     */
    productLinkResponse?: components.ProductLinkResponse | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace CreateProductLinkSecurity$ {
    export const inboundSchema: z.ZodType<CreateProductLinkSecurity, z.ZodTypeDef, unknown> = z
        .object({
            APIKeyHeader: z.string().optional(),
            APIKeyQuery: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                APIKeyHeader: "apiKeyHeader",
                APIKeyQuery: "apiKeyQuery",
            });
        });

    export type Outbound = {
        APIKeyHeader?: string | undefined;
        APIKeyQuery?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateProductLinkSecurity> = z
        .object({
            apiKeyHeader: z.string().optional(),
            apiKeyQuery: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                apiKeyHeader: "APIKeyHeader",
                apiKeyQuery: "APIKeyQuery",
            });
        });
}

/** @internal */
export namespace CreateProductLinkResponse$ {
    export const inboundSchema: z.ZodType<CreateProductLinkResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            ProductLinkResponse: components.ProductLinkResponse$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                ProductLinkResponse: "productLinkResponse",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        ProductLinkResponse?: components.ProductLinkResponse$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateProductLinkResponse> = z
        .object({
            contentType: z.string(),
            productLinkResponse: components.ProductLinkResponse$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                productLinkResponse: "ProductLinkResponse",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
            });
        });
}
