/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type CreateProductLinkSecurity = {
    apiKeyHeader?: string | undefined;
    apiKeyQuery?: string | undefined;
};

export type CreateProductLinkResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Successful Response
     */
    productLinkResponse?: components.ProductLinkResponse | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const CreateProductLinkSecurity$inboundSchema: z.ZodType<
    CreateProductLinkSecurity,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        APIKeyHeader: z.string().optional(),
        APIKeyQuery: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            APIKeyHeader: "apiKeyHeader",
            APIKeyQuery: "apiKeyQuery",
        });
    });

/** @internal */
export type CreateProductLinkSecurity$Outbound = {
    APIKeyHeader?: string | undefined;
    APIKeyQuery?: string | undefined;
};

/** @internal */
export const CreateProductLinkSecurity$outboundSchema: z.ZodType<
    CreateProductLinkSecurity$Outbound,
    z.ZodTypeDef,
    CreateProductLinkSecurity
> = z
    .object({
        apiKeyHeader: z.string().optional(),
        apiKeyQuery: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            apiKeyHeader: "APIKeyHeader",
            apiKeyQuery: "APIKeyQuery",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateProductLinkSecurity$ {
    /** @deprecated use `CreateProductLinkSecurity$inboundSchema` instead. */
    export const inboundSchema = CreateProductLinkSecurity$inboundSchema;
    /** @deprecated use `CreateProductLinkSecurity$outboundSchema` instead. */
    export const outboundSchema = CreateProductLinkSecurity$outboundSchema;
    /** @deprecated use `CreateProductLinkSecurity$Outbound` instead. */
    export type Outbound = CreateProductLinkSecurity$Outbound;
}

/** @internal */
export const CreateProductLinkResponse$inboundSchema: z.ZodType<
    CreateProductLinkResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        ProductLinkResponse: components.ProductLinkResponse$inboundSchema.optional(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            ProductLinkResponse: "productLinkResponse",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type CreateProductLinkResponse$Outbound = {
    ContentType: string;
    ProductLinkResponse?: components.ProductLinkResponse$Outbound | undefined;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const CreateProductLinkResponse$outboundSchema: z.ZodType<
    CreateProductLinkResponse$Outbound,
    z.ZodTypeDef,
    CreateProductLinkResponse
> = z
    .object({
        contentType: z.string(),
        productLinkResponse: components.ProductLinkResponse$outboundSchema.optional(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            productLinkResponse: "ProductLinkResponse",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateProductLinkResponse$ {
    /** @deprecated use `CreateProductLinkResponse$inboundSchema` instead. */
    export const inboundSchema = CreateProductLinkResponse$inboundSchema;
    /** @deprecated use `CreateProductLinkResponse$outboundSchema` instead. */
    export const outboundSchema = CreateProductLinkResponse$outboundSchema;
    /** @deprecated use `CreateProductLinkResponse$Outbound` instead. */
    export type Outbound = CreateProductLinkResponse$Outbound;
}
