/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type QuerySecurity = {
  apiKeyHeader?: string | undefined;
  apiKeyQuery?: string | undefined;
};

export type QueryResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * Successful Response
   */
  queryAPIResponse?: components.QueryAPIResponse | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const QuerySecurity$inboundSchema: z.ZodType<
  QuerySecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  APIKeyHeader: z.string().optional(),
  APIKeyQuery: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "APIKeyHeader": "apiKeyHeader",
    "APIKeyQuery": "apiKeyQuery",
  });
});

/** @internal */
export type QuerySecurity$Outbound = {
  APIKeyHeader?: string | undefined;
  APIKeyQuery?: string | undefined;
};

/** @internal */
export const QuerySecurity$outboundSchema: z.ZodType<
  QuerySecurity$Outbound,
  z.ZodTypeDef,
  QuerySecurity
> = z.object({
  apiKeyHeader: z.string().optional(),
  apiKeyQuery: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    apiKeyHeader: "APIKeyHeader",
    apiKeyQuery: "APIKeyQuery",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QuerySecurity$ {
  /** @deprecated use `QuerySecurity$inboundSchema` instead. */
  export const inboundSchema = QuerySecurity$inboundSchema;
  /** @deprecated use `QuerySecurity$outboundSchema` instead. */
  export const outboundSchema = QuerySecurity$outboundSchema;
  /** @deprecated use `QuerySecurity$Outbound` instead. */
  export type Outbound = QuerySecurity$Outbound;
}

/** @internal */
export const QueryResponse$inboundSchema: z.ZodType<
  QueryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  QueryAPIResponse: components.QueryAPIResponse$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "QueryAPIResponse": "queryAPIResponse",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type QueryResponse$Outbound = {
  ContentType: string;
  QueryAPIResponse?: components.QueryAPIResponse$Outbound | undefined;
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const QueryResponse$outboundSchema: z.ZodType<
  QueryResponse$Outbound,
  z.ZodTypeDef,
  QueryResponse
> = z.object({
  contentType: z.string(),
  queryAPIResponse: components.QueryAPIResponse$outboundSchema.optional(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    queryAPIResponse: "QueryAPIResponse",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryResponse$ {
  /** @deprecated use `QueryResponse$inboundSchema` instead. */
  export const inboundSchema = QueryResponse$inboundSchema;
  /** @deprecated use `QueryResponse$outboundSchema` instead. */
  export const outboundSchema = QueryResponse$outboundSchema;
  /** @deprecated use `QueryResponse$Outbound` instead. */
  export type Outbound = QueryResponse$Outbound;
}
