/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AmountWithCurrency = {
  amount?: number | undefined;
  currency?: string | undefined;
};

/** @internal */
export const AmountWithCurrency$inboundSchema: z.ZodType<
  AmountWithCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number().int().optional(),
  currency: z.string().optional(),
});

/** @internal */
export type AmountWithCurrency$Outbound = {
  amount?: number | undefined;
  currency?: string | undefined;
};

/** @internal */
export const AmountWithCurrency$outboundSchema: z.ZodType<
  AmountWithCurrency$Outbound,
  z.ZodTypeDef,
  AmountWithCurrency
> = z.object({
  amount: z.number().int().optional(),
  currency: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AmountWithCurrency$ {
  /** @deprecated use `AmountWithCurrency$inboundSchema` instead. */
  export const inboundSchema = AmountWithCurrency$inboundSchema;
  /** @deprecated use `AmountWithCurrency$outboundSchema` instead. */
  export const outboundSchema = AmountWithCurrency$outboundSchema;
  /** @deprecated use `AmountWithCurrency$Outbound` instead. */
  export type Outbound = AmountWithCurrency$Outbound;
}
