/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type AmountWithCurrency = {
    amount?: number | undefined;
    currency?: string | undefined;
};

/** @internal */
export namespace AmountWithCurrency$ {
    export const inboundSchema: z.ZodType<AmountWithCurrency, z.ZodTypeDef, unknown> = z.object({
        amount: z.number().int().optional(),
        currency: z.string().optional(),
    });

    export type Outbound = {
        amount?: number | undefined;
        currency?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AmountWithCurrency> = z.object({
        amount: z.number().int().optional(),
        currency: z.string().optional(),
    });
}
