/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ClientDetails = {
  ip: string;
  userAgent?: string | undefined;
};

/** @internal */
export const ClientDetails$inboundSchema: z.ZodType<
  ClientDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  ip: z.string(),
  user_agent: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "user_agent": "userAgent",
  });
});

/** @internal */
export type ClientDetails$Outbound = {
  ip: string;
  user_agent?: string | undefined;
};

/** @internal */
export const ClientDetails$outboundSchema: z.ZodType<
  ClientDetails$Outbound,
  z.ZodTypeDef,
  ClientDetails
> = z.object({
  ip: z.string(),
  userAgent: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    userAgent: "user_agent",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ClientDetails$ {
  /** @deprecated use `ClientDetails$inboundSchema` instead. */
  export const inboundSchema = ClientDetails$inboundSchema;
  /** @deprecated use `ClientDetails$outboundSchema` instead. */
  export const outboundSchema = ClientDetails$outboundSchema;
  /** @deprecated use `ClientDetails$Outbound` instead. */
  export type Outbound = ClientDetails$Outbound;
}

export function clientDetailsToJSON(clientDetails: ClientDetails): string {
  return JSON.stringify(ClientDetails$outboundSchema.parse(clientDetails));
}

export function clientDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ClientDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientDetails' from JSON`,
  );
}
