/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import {
    TaggedLink,
    TaggedLink$inboundSchema,
    TaggedLink$Outbound,
    TaggedLink$outboundSchema,
} from "./taggedlink.js";
import * as z from "zod";

export type EnrichedProduct = {
    extensions?: any | undefined;
    links: TaggedLink;
    referenceId?: string | undefined;
};

/** @internal */
export const EnrichedProduct$inboundSchema: z.ZodType<EnrichedProduct, z.ZodTypeDef, unknown> = z
    .object({
        extensions: z.any().optional(),
        links: TaggedLink$inboundSchema,
        reference_id: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            reference_id: "referenceId",
        });
    });

/** @internal */
export type EnrichedProduct$Outbound = {
    extensions?: any | undefined;
    links: TaggedLink$Outbound;
    reference_id?: string | undefined;
};

/** @internal */
export const EnrichedProduct$outboundSchema: z.ZodType<
    EnrichedProduct$Outbound,
    z.ZodTypeDef,
    EnrichedProduct
> = z
    .object({
        extensions: z.any().optional(),
        links: TaggedLink$outboundSchema,
        referenceId: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            referenceId: "reference_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EnrichedProduct$ {
    /** @deprecated use `EnrichedProduct$inboundSchema` instead. */
    export const inboundSchema = EnrichedProduct$inboundSchema;
    /** @deprecated use `EnrichedProduct$outboundSchema` instead. */
    export const outboundSchema = EnrichedProduct$outboundSchema;
    /** @deprecated use `EnrichedProduct$Outbound` instead. */
    export type Outbound = EnrichedProduct$Outbound;
}
