/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  ExtensionImages,
  ExtensionImages$inboundSchema,
  ExtensionImages$Outbound,
  ExtensionImages$outboundSchema,
} from "./extensionimages.js";
import {
  ExtensionLinks,
  ExtensionLinks$inboundSchema,
  ExtensionLinks$Outbound,
  ExtensionLinks$outboundSchema,
} from "./extensionlinks.js";
import {
  PriceWithCurrency,
  PriceWithCurrency$inboundSchema,
  PriceWithCurrency$Outbound,
  PriceWithCurrency$outboundSchema,
} from "./pricewithcurrency.js";
import {
  ShippingAttribute,
  ShippingAttribute$inboundSchema,
  ShippingAttribute$outboundSchema,
} from "./shippingattribute.js";

export type ExtensionObject = {
  images: ExtensionImages;
  links: ExtensionLinks;
  price: PriceWithCurrency;
  shippingAttributes?: Array<ShippingAttribute> | undefined;
  title: string;
};

/** @internal */
export const ExtensionObject$inboundSchema: z.ZodType<
  ExtensionObject,
  z.ZodTypeDef,
  unknown
> = z.object({
  images: ExtensionImages$inboundSchema,
  links: ExtensionLinks$inboundSchema,
  price: PriceWithCurrency$inboundSchema,
  shipping_attributes: z.array(ShippingAttribute$inboundSchema).optional(),
  title: z.string(),
}).transform((v) => {
  return remap$(v, {
    "shipping_attributes": "shippingAttributes",
  });
});

/** @internal */
export type ExtensionObject$Outbound = {
  images: ExtensionImages$Outbound;
  links: ExtensionLinks$Outbound;
  price: PriceWithCurrency$Outbound;
  shipping_attributes?: Array<string> | undefined;
  title: string;
};

/** @internal */
export const ExtensionObject$outboundSchema: z.ZodType<
  ExtensionObject$Outbound,
  z.ZodTypeDef,
  ExtensionObject
> = z.object({
  images: ExtensionImages$outboundSchema,
  links: ExtensionLinks$outboundSchema,
  price: PriceWithCurrency$outboundSchema,
  shippingAttributes: z.array(ShippingAttribute$outboundSchema).optional(),
  title: z.string(),
}).transform((v) => {
  return remap$(v, {
    shippingAttributes: "shipping_attributes",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExtensionObject$ {
  /** @deprecated use `ExtensionObject$inboundSchema` instead. */
  export const inboundSchema = ExtensionObject$inboundSchema;
  /** @deprecated use `ExtensionObject$outboundSchema` instead. */
  export const outboundSchema = ExtensionObject$outboundSchema;
  /** @deprecated use `ExtensionObject$Outbound` instead. */
  export type Outbound = ExtensionObject$Outbound;
}
