/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ExtensionLinks = {
    original?: string | undefined;
    tagged?: string | undefined;
};

/** @internal */
export namespace ExtensionLinks$ {
    export const inboundSchema: z.ZodType<ExtensionLinks, z.ZodTypeDef, unknown> = z.object({
        original: z.string().optional(),
        tagged: z.string().optional(),
    });

    export type Outbound = {
        original?: string | undefined;
        tagged?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ExtensionLinks> = z.object({
        original: z.string().optional(),
        tagged: z.string().optional(),
    });
}
