/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ExtensionObject, ExtensionObject$ } from "./extensionobject.js";
import * as z from "zod";

export type Extension = {
    data: Array<ExtensionObject>;
};

/** @internal */
export namespace Extension$ {
    export const inboundSchema: z.ZodType<Extension, z.ZodTypeDef, unknown> = z.object({
        data: z.array(ExtensionObject$.inboundSchema),
    });

    export type Outbound = {
        data: Array<ExtensionObject$.Outbound>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Extension> = z.object({
        data: z.array(ExtensionObject$.outboundSchema),
    });
}
