/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ExtensionLinks = {
  original?: string | undefined;
  tagged?: string | undefined;
};

/** @internal */
export const ExtensionLinks$inboundSchema: z.ZodType<
  ExtensionLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  original: z.string().optional(),
  tagged: z.string().optional(),
});

/** @internal */
export type ExtensionLinks$Outbound = {
  original?: string | undefined;
  tagged?: string | undefined;
};

/** @internal */
export const ExtensionLinks$outboundSchema: z.ZodType<
  ExtensionLinks$Outbound,
  z.ZodTypeDef,
  ExtensionLinks
> = z.object({
  original: z.string().optional(),
  tagged: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExtensionLinks$ {
  /** @deprecated use `ExtensionLinks$inboundSchema` instead. */
  export const inboundSchema = ExtensionLinks$inboundSchema;
  /** @deprecated use `ExtensionLinks$outboundSchema` instead. */
  export const outboundSchema = ExtensionLinks$outboundSchema;
  /** @deprecated use `ExtensionLinks$Outbound` instead. */
  export type Outbound = ExtensionLinks$Outbound;
}

export function extensionLinksToJSON(extensionLinks: ExtensionLinks): string {
  return JSON.stringify(ExtensionLinks$outboundSchema.parse(extensionLinks));
}

export function extensionLinksFromJSON(
  jsonString: string,
): SafeParseResult<ExtensionLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExtensionLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtensionLinks' from JSON`,
  );
}
