/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Extension, Extension$ } from "./extension.js";
import * as z from "zod";

export type Extensions = {
    merchants: Extension;
};

/** @internal */
export namespace Extensions$ {
    export const inboundSchema: z.ZodType<Extensions, z.ZodTypeDef, unknown> = z.object({
        merchants: Extension$.inboundSchema,
    });

    export type Outbound = {
        merchants: Extension$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Extensions> = z.object({
        merchants: Extension$.outboundSchema,
    });
}
