/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Extension,
  Extension$inboundSchema,
  Extension$Outbound,
  Extension$outboundSchema,
} from "./extension.js";

export type Extensions = {
  merchants: Extension;
};

/** @internal */
export const Extensions$inboundSchema: z.ZodType<
  Extensions,
  z.ZodTypeDef,
  unknown
> = z.object({
  merchants: Extension$inboundSchema,
});

/** @internal */
export type Extensions$Outbound = {
  merchants: Extension$Outbound;
};

/** @internal */
export const Extensions$outboundSchema: z.ZodType<
  Extensions$Outbound,
  z.ZodTypeDef,
  Extensions
> = z.object({
  merchants: Extension$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Extensions$ {
  /** @deprecated use `Extensions$inboundSchema` instead. */
  export const inboundSchema = Extensions$inboundSchema;
  /** @deprecated use `Extensions$outboundSchema` instead. */
  export const outboundSchema = Extensions$outboundSchema;
  /** @deprecated use `Extensions$Outbound` instead. */
  export type Outbound = Extensions$Outbound;
}

export function extensionsToJSON(extensions: Extensions): string {
  return JSON.stringify(Extensions$outboundSchema.parse(extensions));
}

export function extensionsFromJSON(
  jsonString: string,
): SafeParseResult<Extensions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Extensions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Extensions' from JSON`,
  );
}
