/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ExtensionImages = {
    thumbnail?: string | undefined;
};

/** @internal */
export namespace ExtensionImages$ {
    export const inboundSchema: z.ZodType<ExtensionImages, z.ZodTypeDef, unknown> = z.object({
        thumbnail: z.string().optional(),
    });

    export type Outbound = {
        thumbnail?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ExtensionImages> = z.object({
        thumbnail: z.string().optional(),
    });
}
