/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    Extension,
    Extension$inboundSchema,
    Extension$Outbound,
    Extension$outboundSchema,
} from "./extension.js";
import * as z from "zod";

export type Extensions = {
    merchants: Extension;
};

/** @internal */
export const Extensions$inboundSchema: z.ZodType<Extensions, z.ZodTypeDef, unknown> = z.object({
    merchants: Extension$inboundSchema,
});

/** @internal */
export type Extensions$Outbound = {
    merchants: Extension$Outbound;
};

/** @internal */
export const Extensions$outboundSchema: z.ZodType<Extensions$Outbound, z.ZodTypeDef, Extensions> =
    z.object({
        merchants: Extension$outboundSchema,
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Extensions$ {
    /** @deprecated use `Extensions$inboundSchema` instead. */
    export const inboundSchema = Extensions$inboundSchema;
    /** @deprecated use `Extensions$outboundSchema` instead. */
    export const outboundSchema = Extensions$outboundSchema;
    /** @deprecated use `Extensions$Outbound` instead. */
    export type Outbound = Extensions$Outbound;
}
