/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { ExtensionImages, ExtensionImages$ } from "./extensionimages.js";
import { ExtensionLinks, ExtensionLinks$ } from "./extensionlinks.js";
import { PriceWithCurrency, PriceWithCurrency$ } from "./pricewithcurrency.js";
import { ShippingAttribute, ShippingAttribute$ } from "./shippingattribute.js";
import * as z from "zod";

export type ExtensionObject = {
    images: ExtensionImages;
    links: ExtensionLinks;
    price: PriceWithCurrency;
    shippingAttributes?: Array<ShippingAttribute> | undefined;
    title: string;
};

/** @internal */
export namespace ExtensionObject$ {
    export const inboundSchema: z.ZodType<ExtensionObject, z.ZodTypeDef, unknown> = z
        .object({
            images: ExtensionImages$.inboundSchema,
            links: ExtensionLinks$.inboundSchema,
            price: PriceWithCurrency$.inboundSchema,
            shipping_attributes: z.array(ShippingAttribute$.inboundSchema).optional(),
            title: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                shipping_attributes: "shippingAttributes",
            });
        });

    export type Outbound = {
        images: ExtensionImages$.Outbound;
        links: ExtensionLinks$.Outbound;
        price: PriceWithCurrency$.Outbound;
        shipping_attributes?: Array<string> | undefined;
        title: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ExtensionObject> = z
        .object({
            images: ExtensionImages$.outboundSchema,
            links: ExtensionLinks$.outboundSchema,
            price: PriceWithCurrency$.outboundSchema,
            shippingAttributes: z.array(ShippingAttribute$.outboundSchema).optional(),
            title: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                shippingAttributes: "shipping_attributes",
            });
        });
}
