/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    MessageRole,
    MessageRole$inboundSchema,
    MessageRole$outboundSchema,
} from "./messagerole.js";
import {
    MessageType,
    MessageType$inboundSchema,
    MessageType$outboundSchema,
} from "./messagetype.js";
import * as z from "zod";

export type Message = {
    content: string;
    /**
     * An enumeration.
     */
    role: MessageRole;
    /**
     * An enumeration.
     */
    type: MessageType;
};

/** @internal */
export const Message$inboundSchema: z.ZodType<Message, z.ZodTypeDef, unknown> = z.object({
    content: z.string(),
    role: MessageRole$inboundSchema,
    type: MessageType$inboundSchema,
});

/** @internal */
export type Message$Outbound = {
    content: string;
    role: string;
    type: string;
};

/** @internal */
export const Message$outboundSchema: z.ZodType<Message$Outbound, z.ZodTypeDef, Message> = z.object({
    content: z.string(),
    role: MessageRole$outboundSchema,
    type: MessageType$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Message$ {
    /** @deprecated use `Message$inboundSchema` instead. */
    export const inboundSchema = Message$inboundSchema;
    /** @deprecated use `Message$outboundSchema` instead. */
    export const outboundSchema = Message$outboundSchema;
    /** @deprecated use `Message$Outbound` instead. */
    export type Outbound = Message$Outbound;
}
