/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { MessageRole, MessageRole$ } from "./messagerole";
import { MessageType, MessageType$ } from "./messagetype";
import { z } from "zod";

export type Message = {
    content: string;
    /**
     * An enumeration.
     */
    role: MessageRole;
    /**
     * An enumeration.
     */
    type: MessageType;
};

/** @internal */
export namespace Message$ {
    export type Inbound = {
        content: string;
        role: MessageRole;
        type: MessageType;
    };

    export const inboundSchema: z.ZodType<Message, z.ZodTypeDef, Inbound> = z
        .object({
            content: z.string(),
            role: MessageRole$,
            type: MessageType$,
        })
        .transform((v) => {
            return {
                content: v.content,
                role: v.role,
                type: v.type,
            };
        });

    export type Outbound = {
        content: string;
        role: MessageRole;
        type: MessageType;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Message> = z
        .object({
            content: z.string(),
            role: MessageRole$,
            type: MessageType$,
        })
        .transform((v) => {
            return {
                content: v.content,
                role: v.role,
                type: v.type,
            };
        });
}
