/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

/**
 * An enumeration.
 */
export const MessageRole = {
    User: "user",
    Assistant: "assistant",
    System: "system",
} as const;
/**
 * An enumeration.
 */
export type MessageRole = ClosedEnum<typeof MessageRole>;

/** @internal */
export namespace MessageRole$ {
    export const inboundSchema: z.ZodNativeEnum<typeof MessageRole> = z.nativeEnum(MessageRole);
    export const outboundSchema: z.ZodNativeEnum<typeof MessageRole> = inboundSchema;
}
