/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

/**
 * An enumeration.
 */
export const MessageType = {
    Message: "message",
    Summary: "summary",
    Filter: "filter",
    Tag: "tag",
} as const;
/**
 * An enumeration.
 */
export type MessageType = ClosedEnum<typeof MessageType>;

/** @internal */
export namespace MessageType$ {
    export const inboundSchema: z.ZodNativeEnum<typeof MessageType> = z.nativeEnum(MessageType);
    export const outboundSchema: z.ZodNativeEnum<typeof MessageType> = inboundSchema;
}
