/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * An enumeration.
 */
export enum MessageType {
    Message = "message",
    Summary = "summary",
    Filter = "filter",
    Tag = "tag",
}

/** @internal */
export const MessageType$ = z.nativeEnum(MessageType);
