/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { MessageRole, MessageRole$ } from "./messagerole.js";
import { MessageType, MessageType$ } from "./messagetype.js";
import * as z from "zod";

export type Message = {
    content: string;
    /**
     * An enumeration.
     */
    role: MessageRole;
    /**
     * An enumeration.
     */
    type: MessageType;
};

/** @internal */
export namespace Message$ {
    export const inboundSchema: z.ZodType<Message, z.ZodTypeDef, unknown> = z.object({
        content: z.string(),
        role: MessageRole$.inboundSchema,
        type: MessageType$.inboundSchema,
    });

    export type Outbound = {
        content: string;
        role: string;
        type: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Message> = z.object({
        content: z.string(),
        role: MessageRole$.outboundSchema,
        type: MessageType$.outboundSchema,
    });
}
