/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type PriceWithCurrency = {
    amount: number;
    currency: string;
};

/** @internal */
export namespace PriceWithCurrency$ {
    export const inboundSchema: z.ZodType<PriceWithCurrency, z.ZodTypeDef, unknown> = z.object({
        amount: z.number().int(),
        currency: z.string(),
    });

    export type Outbound = {
        amount: number;
        currency: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PriceWithCurrency> = z.object({
        amount: z.number().int(),
        currency: z.string(),
    });
}
