/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PriceWithCurrency = {
  amount: number;
  currency: string;
};

/** @internal */
export const PriceWithCurrency$inboundSchema: z.ZodType<
  PriceWithCurrency,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number().int(),
  currency: z.string(),
});

/** @internal */
export type PriceWithCurrency$Outbound = {
  amount: number;
  currency: string;
};

/** @internal */
export const PriceWithCurrency$outboundSchema: z.ZodType<
  PriceWithCurrency$Outbound,
  z.ZodTypeDef,
  PriceWithCurrency
> = z.object({
  amount: z.number().int(),
  currency: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PriceWithCurrency$ {
  /** @deprecated use `PriceWithCurrency$inboundSchema` instead. */
  export const inboundSchema = PriceWithCurrency$inboundSchema;
  /** @deprecated use `PriceWithCurrency$outboundSchema` instead. */
  export const outboundSchema = PriceWithCurrency$outboundSchema;
  /** @deprecated use `PriceWithCurrency$Outbound` instead. */
  export type Outbound = PriceWithCurrency$Outbound;
}
