/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ProductIdentifiers = {
    asin?: string | undefined;
    ean?: string | undefined;
    gtin?: string | undefined;
    isbn?: string | undefined;
    sku?: string | undefined;
    tcin?: string | undefined;
    upc?: string | undefined;
};

/** @internal */
export namespace ProductIdentifiers$ {
    export const inboundSchema: z.ZodType<ProductIdentifiers, z.ZodTypeDef, unknown> = z.object({
        asin: z.string().optional(),
        ean: z.string().optional(),
        gtin: z.string().optional(),
        isbn: z.string().optional(),
        sku: z.string().optional(),
        tcin: z.string().optional(),
        upc: z.string().optional(),
    });

    export type Outbound = {
        asin?: string | undefined;
        ean?: string | undefined;
        gtin?: string | undefined;
        isbn?: string | undefined;
        sku?: string | undefined;
        tcin?: string | undefined;
        upc?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ProductIdentifiers> = z.object({
        asin: z.string().optional(),
        ean: z.string().optional(),
        gtin: z.string().optional(),
        isbn: z.string().optional(),
        sku: z.string().optional(),
        tcin: z.string().optional(),
        upc: z.string().optional(),
    });
}
