/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ClientDetails,
  ClientDetails$inboundSchema,
  ClientDetails$Outbound,
  ClientDetails$outboundSchema,
} from "./clientdetails.js";
import {
  ProductDetails,
  ProductDetails$inboundSchema,
  ProductDetails$Outbound,
  ProductDetails$outboundSchema,
} from "./productdetails.js";
import {
  QueryDetails,
  QueryDetails$inboundSchema,
  QueryDetails$Outbound,
  QueryDetails$outboundSchema,
} from "./querydetails.js";
import {
  UserDetails,
  UserDetails$inboundSchema,
  UserDetails$Outbound,
  UserDetails$outboundSchema,
} from "./userdetails.js";

export type ProductLinkRequest = {
  clientDetails: ClientDetails;
  idempotencyKey?: string | undefined;
  logOnly?: boolean | undefined;
  product: ProductDetails;
  query: QueryDetails;
  referenceId?: string | undefined;
  userDetails: UserDetails;
};

/** @internal */
export const ProductLinkRequest$inboundSchema: z.ZodType<
  ProductLinkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  client_details: ClientDetails$inboundSchema,
  idempotency_key: z.string().optional(),
  log_only: z.boolean().default(false),
  product: ProductDetails$inboundSchema,
  query: QueryDetails$inboundSchema,
  reference_id: z.string().optional(),
  user_details: UserDetails$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "client_details": "clientDetails",
    "idempotency_key": "idempotencyKey",
    "log_only": "logOnly",
    "reference_id": "referenceId",
    "user_details": "userDetails",
  });
});

/** @internal */
export type ProductLinkRequest$Outbound = {
  client_details: ClientDetails$Outbound;
  idempotency_key?: string | undefined;
  log_only: boolean;
  product: ProductDetails$Outbound;
  query: QueryDetails$Outbound;
  reference_id?: string | undefined;
  user_details: UserDetails$Outbound;
};

/** @internal */
export const ProductLinkRequest$outboundSchema: z.ZodType<
  ProductLinkRequest$Outbound,
  z.ZodTypeDef,
  ProductLinkRequest
> = z.object({
  clientDetails: ClientDetails$outboundSchema,
  idempotencyKey: z.string().optional(),
  logOnly: z.boolean().default(false),
  product: ProductDetails$outboundSchema,
  query: QueryDetails$outboundSchema,
  referenceId: z.string().optional(),
  userDetails: UserDetails$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    clientDetails: "client_details",
    idempotencyKey: "idempotency_key",
    logOnly: "log_only",
    referenceId: "reference_id",
    userDetails: "user_details",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProductLinkRequest$ {
  /** @deprecated use `ProductLinkRequest$inboundSchema` instead. */
  export const inboundSchema = ProductLinkRequest$inboundSchema;
  /** @deprecated use `ProductLinkRequest$outboundSchema` instead. */
  export const outboundSchema = ProductLinkRequest$outboundSchema;
  /** @deprecated use `ProductLinkRequest$Outbound` instead. */
  export type Outbound = ProductLinkRequest$Outbound;
}

export function productLinkRequestToJSON(
  productLinkRequest: ProductLinkRequest,
): string {
  return JSON.stringify(
    ProductLinkRequest$outboundSchema.parse(productLinkRequest),
  );
}

export function productLinkRequestFromJSON(
  jsonString: string,
): SafeParseResult<ProductLinkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductLinkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductLinkRequest' from JSON`,
  );
}
