/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AmountWithCurrency,
  AmountWithCurrency$inboundSchema,
  AmountWithCurrency$Outbound,
  AmountWithCurrency$outboundSchema,
} from "./amountwithcurrency.js";
import {
  ProductIdentifiers,
  ProductIdentifiers$inboundSchema,
  ProductIdentifiers$Outbound,
  ProductIdentifiers$outboundSchema,
} from "./productidentifiers.js";

export type ProductDetails = {
  identifiers: ProductIdentifiers;
  imageUrl?: string | undefined;
  link: string;
  price?: AmountWithCurrency | undefined;
  referenceId?: string | undefined;
  title?: string | undefined;
};

/** @internal */
export const ProductDetails$inboundSchema: z.ZodType<
  ProductDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  identifiers: ProductIdentifiers$inboundSchema,
  image_url: z.string().optional(),
  link: z.string(),
  price: AmountWithCurrency$inboundSchema.optional(),
  reference_id: z.string().optional(),
  title: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "image_url": "imageUrl",
    "reference_id": "referenceId",
  });
});

/** @internal */
export type ProductDetails$Outbound = {
  identifiers: ProductIdentifiers$Outbound;
  image_url?: string | undefined;
  link: string;
  price?: AmountWithCurrency$Outbound | undefined;
  reference_id?: string | undefined;
  title?: string | undefined;
};

/** @internal */
export const ProductDetails$outboundSchema: z.ZodType<
  ProductDetails$Outbound,
  z.ZodTypeDef,
  ProductDetails
> = z.object({
  identifiers: ProductIdentifiers$outboundSchema,
  imageUrl: z.string().optional(),
  link: z.string(),
  price: AmountWithCurrency$outboundSchema.optional(),
  referenceId: z.string().optional(),
  title: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    imageUrl: "image_url",
    referenceId: "reference_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProductDetails$ {
  /** @deprecated use `ProductDetails$inboundSchema` instead. */
  export const inboundSchema = ProductDetails$inboundSchema;
  /** @deprecated use `ProductDetails$outboundSchema` instead. */
  export const outboundSchema = ProductDetails$outboundSchema;
  /** @deprecated use `ProductDetails$Outbound` instead. */
  export type Outbound = ProductDetails$Outbound;
}

export function productDetailsToJSON(productDetails: ProductDetails): string {
  return JSON.stringify(ProductDetails$outboundSchema.parse(productDetails));
}

export function productDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ProductDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductDetails' from JSON`,
  );
}
