/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  EnrichedProduct,
  EnrichedProduct$inboundSchema,
  EnrichedProduct$Outbound,
  EnrichedProduct$outboundSchema,
} from "./enrichedproduct.js";

export type ProductLinkResponse = {
  id: string;
  idempotencyKey?: string | undefined;
  product: EnrichedProduct;
  referenceId?: string | undefined;
};

/** @internal */
export const ProductLinkResponse$inboundSchema: z.ZodType<
  ProductLinkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  idempotency_key: z.string().optional(),
  product: EnrichedProduct$inboundSchema,
  reference_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "idempotency_key": "idempotencyKey",
    "reference_id": "referenceId",
  });
});

/** @internal */
export type ProductLinkResponse$Outbound = {
  id: string;
  idempotency_key?: string | undefined;
  product: EnrichedProduct$Outbound;
  reference_id?: string | undefined;
};

/** @internal */
export const ProductLinkResponse$outboundSchema: z.ZodType<
  ProductLinkResponse$Outbound,
  z.ZodTypeDef,
  ProductLinkResponse
> = z.object({
  id: z.string(),
  idempotencyKey: z.string().optional(),
  product: EnrichedProduct$outboundSchema,
  referenceId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency_key",
    referenceId: "reference_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProductLinkResponse$ {
  /** @deprecated use `ProductLinkResponse$inboundSchema` instead. */
  export const inboundSchema = ProductLinkResponse$inboundSchema;
  /** @deprecated use `ProductLinkResponse$outboundSchema` instead. */
  export const outboundSchema = ProductLinkResponse$outboundSchema;
  /** @deprecated use `ProductLinkResponse$Outbound` instead. */
  export type Outbound = ProductLinkResponse$Outbound;
}
