/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type Query = {
  maxPrice?: number | undefined;
  minPrice?: number | undefined;
  numResults?: number | undefined;
  query: string;
};

/** @internal */
export const Query$inboundSchema: z.ZodType<Query, z.ZodTypeDef, unknown> = z
  .object({
    max_price: z.number().int().optional(),
    min_price: z.number().int().optional(),
    num_results: z.number().int().default(5),
    query: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "max_price": "maxPrice",
      "min_price": "minPrice",
      "num_results": "numResults",
    });
  });

/** @internal */
export type Query$Outbound = {
  max_price?: number | undefined;
  min_price?: number | undefined;
  num_results: number;
  query: string;
};

/** @internal */
export const Query$outboundSchema: z.ZodType<
  Query$Outbound,
  z.ZodTypeDef,
  Query
> = z.object({
  maxPrice: z.number().int().optional(),
  minPrice: z.number().int().optional(),
  numResults: z.number().int().default(5),
  query: z.string(),
}).transform((v) => {
  return remap$(v, {
    maxPrice: "max_price",
    minPrice: "min_price",
    numResults: "num_results",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Query$ {
  /** @deprecated use `Query$inboundSchema` instead. */
  export const inboundSchema = Query$inboundSchema;
  /** @deprecated use `Query$outboundSchema` instead. */
  export const outboundSchema = Query$outboundSchema;
  /** @deprecated use `Query$Outbound` instead. */
  export type Outbound = Query$Outbound;
}
