/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Product,
  Product$inboundSchema,
  Product$Outbound,
  Product$outboundSchema,
} from "./product.js";
import {
  Query,
  Query$inboundSchema,
  Query$Outbound,
  Query$outboundSchema,
} from "./query.js";

export type QueryResult = {
  products: Array<Product>;
  query: Query;
};

/** @internal */
export const QueryResult$inboundSchema: z.ZodType<
  QueryResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  products: z.array(Product$inboundSchema),
  query: Query$inboundSchema,
});

/** @internal */
export type QueryResult$Outbound = {
  products: Array<Product$Outbound>;
  query: Query$Outbound;
};

/** @internal */
export const QueryResult$outboundSchema: z.ZodType<
  QueryResult$Outbound,
  z.ZodTypeDef,
  QueryResult
> = z.object({
  products: z.array(Product$outboundSchema),
  query: Query$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryResult$ {
  /** @deprecated use `QueryResult$inboundSchema` instead. */
  export const inboundSchema = QueryResult$inboundSchema;
  /** @deprecated use `QueryResult$outboundSchema` instead. */
  export const outboundSchema = QueryResult$outboundSchema;
  /** @deprecated use `QueryResult$Outbound` instead. */
  export type Outbound = QueryResult$Outbound;
}

export function queryResultToJSON(queryResult: QueryResult): string {
  return JSON.stringify(QueryResult$outboundSchema.parse(queryResult));
}

export function queryResultFromJSON(
  jsonString: string,
): SafeParseResult<QueryResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryResult' from JSON`,
  );
}
