/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type Query = {
    query: string;
    numResults?: number | undefined;
    minPrice?: number | undefined;
    maxPrice?: number | undefined;
};

/** @internal */
export namespace Query$ {
    export type Inbound = {
        query: string;
        num_results?: number | undefined;
        min_price?: number | undefined;
        max_price?: number | undefined;
    };

    export const inboundSchema: z.ZodType<Query, z.ZodTypeDef, Inbound> = z
        .object({
            query: z.string(),
            num_results: z.number().int().default(5),
            min_price: z.number().int().optional(),
            max_price: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                query: v.query,
                numResults: v.num_results,
                ...(v.min_price === undefined ? null : { minPrice: v.min_price }),
                ...(v.max_price === undefined ? null : { maxPrice: v.max_price }),
            };
        });

    export type Outbound = {
        query: string;
        num_results: number;
        min_price?: number | undefined;
        max_price?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Query> = z
        .object({
            query: z.string(),
            numResults: z.number().int().default(5),
            minPrice: z.number().int().optional(),
            maxPrice: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                query: v.query,
                num_results: v.numResults,
                ...(v.minPrice === undefined ? null : { min_price: v.minPrice }),
                ...(v.maxPrice === undefined ? null : { max_price: v.maxPrice }),
            };
        });
}
