/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    Message,
    Message$inboundSchema,
    Message$Outbound,
    Message$outboundSchema,
} from "./message.js";
import { Query, Query$inboundSchema, Query$Outbound, Query$outboundSchema } from "./query.js";
import {
    Session,
    Session$inboundSchema,
    Session$Outbound,
    Session$outboundSchema,
} from "./session.js";
import * as z from "zod";

export type QueryAPIRequest = {
    messages?: Array<Message> | undefined;
    query: Query;
    session?: Session | undefined;
};

/** @internal */
export const QueryAPIRequest$inboundSchema: z.ZodType<QueryAPIRequest, z.ZodTypeDef, unknown> =
    z.object({
        messages: z.array(Message$inboundSchema).optional(),
        query: Query$inboundSchema,
        session: Session$inboundSchema.optional(),
    });

/** @internal */
export type QueryAPIRequest$Outbound = {
    messages?: Array<Message$Outbound> | undefined;
    query: Query$Outbound;
    session?: Session$Outbound | undefined;
};

/** @internal */
export const QueryAPIRequest$outboundSchema: z.ZodType<
    QueryAPIRequest$Outbound,
    z.ZodTypeDef,
    QueryAPIRequest
> = z.object({
    messages: z.array(Message$outboundSchema).optional(),
    query: Query$outboundSchema,
    session: Session$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryAPIRequest$ {
    /** @deprecated use `QueryAPIRequest$inboundSchema` instead. */
    export const inboundSchema = QueryAPIRequest$inboundSchema;
    /** @deprecated use `QueryAPIRequest$outboundSchema` instead. */
    export const outboundSchema = QueryAPIRequest$outboundSchema;
    /** @deprecated use `QueryAPIRequest$Outbound` instead. */
    export type Outbound = QueryAPIRequest$Outbound;
}
