/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type QueryDetails = {
    q: string;
};

/** @internal */
export namespace QueryDetails$ {
    export const inboundSchema: z.ZodType<QueryDetails, z.ZodTypeDef, unknown> = z.object({
        q: z.string(),
    });

    export type Outbound = {
        q: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, QueryDetails> = z.object({
        q: z.string(),
    });
}
