/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QueryDetails = {
  q: string;
};

/** @internal */
export const QueryDetails$inboundSchema: z.ZodType<
  QueryDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  q: z.string(),
});

/** @internal */
export type QueryDetails$Outbound = {
  q: string;
};

/** @internal */
export const QueryDetails$outboundSchema: z.ZodType<
  QueryDetails$Outbound,
  z.ZodTypeDef,
  QueryDetails
> = z.object({
  q: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryDetails$ {
  /** @deprecated use `QueryDetails$inboundSchema` instead. */
  export const inboundSchema = QueryDetails$inboundSchema;
  /** @deprecated use `QueryDetails$outboundSchema` instead. */
  export const outboundSchema = QueryDetails$outboundSchema;
  /** @deprecated use `QueryDetails$Outbound` instead. */
  export type Outbound = QueryDetails$Outbound;
}

export function queryDetailsToJSON(queryDetails: QueryDetails): string {
  return JSON.stringify(QueryDetails$outboundSchema.parse(queryDetails));
}

export function queryDetailsFromJSON(
  jsonString: string,
): SafeParseResult<QueryDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryDetails' from JSON`,
  );
}
