/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Product, Product$ } from "./product.js";
import { Query, Query$ } from "./query.js";
import * as z from "zod";

export type QueryResult = {
    products: Array<Product>;
    query: Query;
};

/** @internal */
export namespace QueryResult$ {
    export const inboundSchema: z.ZodType<QueryResult, z.ZodTypeDef, unknown> = z.object({
        products: z.array(Product$.inboundSchema),
        query: Query$.inboundSchema,
    });

    export type Outbound = {
        products: Array<Product$.Outbound>;
        query: Query$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, QueryResult> = z.object({
        products: z.array(Product$.outboundSchema),
        query: Query$.outboundSchema,
    });
}
