/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type Security = {
    apiKeyHeader?: string | undefined;
};

/** @internal */
export namespace Security$ {
    export const inboundSchema: z.ZodType<Security, z.ZodTypeDef, unknown> = z
        .object({
            APIKeyHeader: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                APIKeyHeader: "apiKeyHeader",
            });
        });

    export type Outbound = {
        APIKeyHeader?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Security> = z
        .object({
            apiKeyHeader: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                apiKeyHeader: "APIKeyHeader",
            });
        });
}
