/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type Session = {
  locale?: string | undefined;
  sessionId?: string | undefined;
  userId?: string | undefined;
};

/** @internal */
export const Session$inboundSchema: z.ZodType<Session, z.ZodTypeDef, unknown> =
  z.object({
    locale: z.string().default("en-US"),
    session_id: z.string().optional(),
    user_id: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "session_id": "sessionId",
      "user_id": "userId",
    });
  });

/** @internal */
export type Session$Outbound = {
  locale: string;
  session_id?: string | undefined;
  user_id?: string | undefined;
};

/** @internal */
export const Session$outboundSchema: z.ZodType<
  Session$Outbound,
  z.ZodTypeDef,
  Session
> = z.object({
  locale: z.string().default("en-US"),
  sessionId: z.string().optional(),
  userId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    sessionId: "session_id",
    userId: "user_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Session$ {
  /** @deprecated use `Session$inboundSchema` instead. */
  export const inboundSchema = Session$inboundSchema;
  /** @deprecated use `Session$outboundSchema` instead. */
  export const outboundSchema = Session$outboundSchema;
  /** @deprecated use `Session$Outbound` instead. */
  export type Outbound = Session$Outbound;
}
