/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

/**
 * An enumeration.
 */
export const ShippingAttribute = {
    FreeShipping: "free_shipping",
    OneDayShipping: "one_day_shipping",
    TwoDayShipping: "two_day_shipping",
    InStorePickup: "in_store_pickup",
} as const;
/**
 * An enumeration.
 */
export type ShippingAttribute = ClosedEnum<typeof ShippingAttribute>;

/** @internal */
export const ShippingAttribute$inboundSchema: z.ZodNativeEnum<typeof ShippingAttribute> =
    z.nativeEnum(ShippingAttribute);

/** @internal */
export const ShippingAttribute$outboundSchema: z.ZodNativeEnum<typeof ShippingAttribute> =
    ShippingAttribute$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ShippingAttribute$ {
    /** @deprecated use `ShippingAttribute$inboundSchema` instead. */
    export const inboundSchema = ShippingAttribute$inboundSchema;
    /** @deprecated use `ShippingAttribute$outboundSchema` instead. */
    export const outboundSchema = ShippingAttribute$outboundSchema;
}
