/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type TaggedLink = {
    original: string;
    tagged: string;
};

/** @internal */
export namespace TaggedLink$ {
    export const inboundSchema: z.ZodType<TaggedLink, z.ZodTypeDef, unknown> = z.object({
        original: z.string(),
        tagged: z.string(),
    });

    export type Outbound = {
        original: string;
        tagged: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, TaggedLink> = z.object({
        original: z.string(),
        tagged: z.string(),
    });
}
