/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type UserDetails = {
    email: string;
    id: string;
    postalCode?: string | undefined;
};

/** @internal */
export const UserDetails$inboundSchema: z.ZodType<UserDetails, z.ZodTypeDef, unknown> = z
    .object({
        email: z.string(),
        id: z.string(),
        postal_code: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            postal_code: "postalCode",
        });
    });

/** @internal */
export type UserDetails$Outbound = {
    email: string;
    id: string;
    postal_code?: string | undefined;
};

/** @internal */
export const UserDetails$outboundSchema: z.ZodType<
    UserDetails$Outbound,
    z.ZodTypeDef,
    UserDetails
> = z
    .object({
        email: z.string(),
        id: z.string(),
        postalCode: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            postalCode: "postal_code",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserDetails$ {
    /** @deprecated use `UserDetails$inboundSchema` instead. */
    export const inboundSchema = UserDetails$inboundSchema;
    /** @deprecated use `UserDetails$outboundSchema` instead. */
    export const outboundSchema = UserDetails$outboundSchema;
    /** @deprecated use `UserDetails$Outbound` instead. */
    export type Outbound = UserDetails$Outbound;
}
